# Generated by Django 6.0.2 on 2026-02-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_uid', models.CharField(db_index=True, max_length=128)),
                ('disease_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('is_healthy', models.BooleanField(default=False)),
                ('raw_label', models.CharField(blank=True, default='', max_length=255)),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disease Prediction',
                'verbose_name_plural': 'Disease Predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
