# Generated by Django 6.0.2 on 2026-02-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseprediction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='disease_images/'),
        ),
    ]
