# Generated by Django 6.0.2 on 2026-02-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Chennai', max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('wind_speed', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('rainfall', models.FloatField(default=0.0)),
                ('clouds', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
