# Generated by Django 6.0.2 on 2026-02-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uid', models.CharField(help_text='Firebase UID', max_length=128, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('location', models.CharField(default='Chennai', help_text='Preferred city for weather', max_length=255)),
                ('language', models.CharField(default='en', help_text='Preferred language code (en, ta, etc.)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
